version: "3.9"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always
    environment:
      MYSQL_DATABASE: demo_database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - netw

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
    networks:
      - netw
networks:
  netw:
